### PR TITLE
initial commit of governance text translated from markdown

### PR DESCRIPTION
**Pull request by kathrynmohror**
Translated text using pandoc
Added latex template framework
Added table of contents
Added subsections to help navigate document
Attempted to add consistency to formatting of terms, e.g. Straw Poll, Participant throughout document. Terms are in italics on first use, then capitalized in document. Labels and other Github status markers use quotation marks.

### CODE REVIEW

**Comment by kathrynmohror** [comment]
Please use emoji reactions ON THIS COMMENT to indicate your position on this proposal.

    * You do not need to vote on every proposal
    * If you have no opinion, don't vote - that is also useful data
    * If you've already commented on this issue, please still vote so
          we know your current thoughts
    * Not all proposals solve exactly the same problem, so we may end
          up accepting proposals that appear to have some overlap

This is not a binding majority-rule vote, but it will be a very
significant input into the corresponding ASC decision.

Here are the meanings for the emojis:

    * Hooray or Rocket: I support this so strongly that I
          want to be an advocate for it
    * Heart: I think this is an ideal solution
    * Thumbs up: I'd be happy with this solution
    * Confused: I'd rather we not do this, but I can tolerate it
    * Thumbs down: I'd be actively unhappy, and may even consider
          other technologies instead

If you want to explain in more detail, feel free to add another
comment, but please also vote on this comment.

**Comment by jjhursey** [comment]
I would like to keep the Straw Poll comment as an additional markdown or plain text file in this repo. That will make it easier to copy/paste into PRs than trying to do so from the PDF.

The document looks good to me. Thanks!

**Comment by kathrynmohror** [comment]
@jjhursey I'm happy to add it as part of this PR because I agree that will make things easier. Where should it go in the repository? A file called StrawPollComment.txt perhaps ?

**Comment by jjhursey** [comment]
That sounds fine to me. Thanks!

**Comment by kathrynmohror** [comment]
@jjhursey I just added the straw poll comment text

**Pull request merged**
