### PR TITLE
Update major release guidance

### PR DESCRIPTION
**Pull request by raffenet**
Remove face-to-face meeting requirement for major release approval, and
updating surrounding text. Retain limit of one major release per year.

### CODE REVIEW

**Comment by raffenet** [comment]
Here's my stab at updating the major release guidance. Please give your feedback!
cc: @dsolt

**Review by dsolt — COMMENTED** [review]
This looks good to me.

**Comment by kathrynmohror** [comment]
Please use emoji reactions ON THIS COMMENT to indicate your position on this proposal.

* You do not need to vote on every proposal
* If you have no opinion, don't vote - that is also useful data
* If you've already commented on this issue, please still vote so
      we know your current thoughts
* Not all proposals solve exactly the same problem, so we may end
      up accepting proposals that appear to have some overlap
This is not a binding majority-rule vote, but it will be a very
significant input into the corresponding ASC decision.

Here are the meanings for the emojis:

* Hooray or Rocket: I support this so strongly that I
      want to be an advocate for it
* Heart: I think this is an ideal solution
* Thumbs up: I'd be happy with this solution
* Confused: I'd rather we not do this, but I can tolerate it
* Thumbs down: I'd be actively unhappy, and may even consider
      other technologies instead
If you want to explain in more detail, feel free to add another
comment, but please also vote on this comment.

**Comment by jjhursey** [comment]
PMIx ASC 1Q 2022

 * Passed the first vote: 11 yes / 0 no / 0 abstain
 * This is eligible for second vote in the 2Q 2022 ASC quarterly meeting

**Comment by jjhursey** [comment]
PMIx ASC 2Q 2022
 * Passed the second vote: 11 yes / 0 no / 0 abstain
 * Will be merged into the next release

**Review by jjhursey — APPROVED** [review]

**Pull request merged**
